%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-sdformat-vendor
Version:        0.2.3
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS sdformat_vendor package

License:        Apache License 2.0
URL:            https://github.com/gazebosim/sdformat
Source0:        %{name}-%{version}.tar.gz

Requires:       pybind11-devel
Requires:       ros-rolling-gz-cmake-vendor
Requires:       ros-rolling-gz-math-vendor
Requires:       ros-rolling-gz-tools-vendor
Requires:       ros-rolling-gz-utils-vendor
Requires:       ros-rolling-urdfdom
Requires:       tinyxml2-devel
Requires:       ros-rolling-ros-workspace
BuildRequires:  cmake3
BuildRequires:  pybind11-devel
BuildRequires:  ros-rolling-ament-cmake-core
BuildRequires:  ros-rolling-ament-cmake-test
BuildRequires:  ros-rolling-ament-cmake-vendor-package
BuildRequires:  ros-rolling-gz-cmake-vendor
BuildRequires:  ros-rolling-gz-math-vendor
BuildRequires:  ros-rolling-gz-tools-vendor
BuildRequires:  ros-rolling-gz-utils-vendor
BuildRequires:  ros-rolling-urdfdom
BuildRequires:  tinyxml2-devel
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  libxml2
BuildRequires:  python%{python3_pkgversion}-psutil
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-rolling-ament-cmake-copyright
BuildRequires:  ros-rolling-ament-cmake-lint-cmake
BuildRequires:  ros-rolling-ament-cmake-xmllint
%endif

%description
Vendor package for: sdformat15 15.1.1 SDFormat is an XML file format that
describes environments, objects, and robots in a manner suitable for robotic
applications

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Tue Nov 26 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.2.3-2
- Autogenerated by Bloom

* Tue Nov 26 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.2.3-1
- Autogenerated by Bloom

* Thu Nov 14 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.2.2-1
- Autogenerated by Bloom

* Tue Nov 05 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.2.1-1
- Autogenerated by Bloom

* Mon Sep 30 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.2.0-1
- Autogenerated by Bloom

* Thu Aug 08 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.1.3-1
- Autogenerated by Bloom

* Mon Jul 15 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.1.2-1
- Autogenerated by Bloom

* Wed May 29 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.1.1-1
- Autogenerated by Bloom

* Tue Apr 23 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.1.0-1
- Autogenerated by Bloom

* Tue Apr 09 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.0.3-1
- Autogenerated by Bloom

* Fri Mar 29 2024 Addisu Z. Taddese <addisuzt@intrinsic.ai> - 0.0.2-1
- Autogenerated by Bloom

